spring:
  datasource:
    url: jdbc:mysql://localhost:3306/whenyourcar
    username: root
    password: 0782
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      topic:
        chatQueue: chatQueue
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      virtual-host: /

rabbitmq:
  chat-queue:
    name: "chat.user."
  chat-exchange:
    name: "chat.exchange"

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.amqp: DEBUG

server:
  port: 8081
