spring:
  datasource:
    url: jdbc:mysql://10.0.1.110:3306/whenyourcar
    username: user
    password: '@Opyuhepl758'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: 10.0.1.23
      port: 6379
      topic:
        chatQueue: chatQueue
    rabbitmq:
      host: 10.0.1.23
      port: 5672
      username: guest
      password: guest
      virtual-host: /

rabbitmq:
  chat-queue:
    name: "chat.user."
  chat-exchange:
    name: "chat.exchange"

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.amqp: DEBUG

server:
  port: 8081
